role_based_access/role_based_access/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('usr_role.urls'), name="usr_role")
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

role_based_access/usr_role/urls.py
from django.urls import path
from .import  views
from django.views.generic import TemplateView

app_name = 'usr_role'

urlpatterns=[
    path('success/', TemplateView.as_view(template_name='user_role/success.html'), name='success'),
    path('doctor/', views.DoctorRegisteration.as_view(), name='doctor_register'),
    path('patient/', views.PatientRegisteration.as_view(), name='patient_register'),
    path('login/',views.LoginView.as_view(), name='login'),
    path('logout/',views.LogoutView.as_view(), name='logout'),
    path('register/', TemplateView.as_view(template_name='user_role/register.html'), name='register'),
    path('patient-home/', views.PatientDashboardView.as_view(), name='patient'),
    path('doctor-home/', views.DoctorDashboardView.as_view(), name='doctor'),
    # path('patient-home/', TemplateView.as_view(template_name='user_role/patient_dashboard.html'), name='patient'),
    # path('doctor-home/', TemplateView.as_view(template_name='user_role/doctor_dashboard.html'), name='doctor'),
]

role_based_access/usr_role/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class BaseUser(AbstractUser):
    is_doctor = models.BooleanField(default=False)
    is_patient = models.BooleanField(default=False)
    address = models.TextField(max_length=200)

class Doctor(models.Model):
    user = models.OneToOneField(BaseUser, on_delete = models.CASCADE, primary_key = True)
    doctor_profile = models.ImageField(upload_to='profiles/', blank=True)

    def __str__(self):
        return self.user.username

class Patient(models.Model):
    user = models.OneToOneField(BaseUser, on_delete = models.CASCADE, primary_key = True)
    patient_profile = models.ImageField(upload_to='profiles/', blank=True)

    def __str__(self):
        return self.user.username

role_based_access/usr_role/forms.py
from django import forms
from usr_role.models import BaseUser, Doctor, Patient
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class PatientSignUpForm(UserCreationForm):
    patient_profile = forms.ImageField()

    class Meta(UserCreationForm.Meta):
        model = BaseUser
        fields = ("patient_profile", "first_name", "last_name", "email", "username", "password1", "password2", "address")
    
    def save(self):
        user = super().save(commit=False)
        user.is_patient = True
        user.username = self.cleaned_data.get('username')
        user.save()

        patient_profile = self.cleaned_data['patient_profile']
        if patient_profile:
            patient = Patient.objects.create(user=user, patient_profile=patient_profile)
            patient.save()
        return user

class DoctorSignUpForm(UserCreationForm):
    doctor_profile = forms.ImageField()

    class Meta(UserCreationForm.Meta):
        model = BaseUser
        fields = ("doctor_profile", "first_name", "last_name", "email", "username", "password1", "password2", "address")

    def save(self):
        user = super().save(commit=False)
        user.is_doctor = True
        user.is_staff = True
        user.username = self.cleaned_data.get('username')
        user.save()

        doctor_profile = self.cleaned_data['doctor_profile']
        if doctor_profile:
            doctor = Doctor.objects.create(user=user, doctor_profile=doctor_profile)
            doctor.save()
        return user
    
class LoginForm(AuthenticationForm):
    password = forms.CharField(widget=forms.PasswordInput)

role_based_access/usr_role/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth import login, logout,authenticate
from django.views.generic import CreateView, RedirectView, TemplateView, FormView
from usr_role.models import BaseUser, Doctor, Patient
from usr_role.forms import UserCreationForm, DoctorSignUpForm, PatientSignUpForm, LoginForm

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'user_role/login.html'

    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)
        
    def get_success_url(self):
        if self.request.user.is_patient:
            return reverse_lazy('usr_role:patient')
        elif self.request.user.is_doctor:
            return reverse_lazy('usr_role:doctor')
        else:
            return reverse_lazy('usr_role:login')

class DoctorRegisteration(CreateView):
    model = Doctor
    form_class = DoctorSignUpForm
    template_name = 'user_role/doctor_register.html'
    success_url = reverse_lazy('usr_role:login')
    success_message = 'Congratulation, Registration successful | Please login to continue !!!!'

    # for directly redirect to userpage after user_registration
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('usr_role:doctor')

class PatientRegisteration(CreateView):
    model = Patient
    form_class = PatientSignUpForm
    template_name = 'user_role/patient_register.html'
    success_url = reverse_lazy('usr_role:login')
    success_message = 'Congratulation, Registration successful | Please login to continue !!!!'
    
    # for directly redirect to userpage after user_registration
    # def form_valid(self, form):
    #     user = form.save()
    #     login(self.request, user)
    #     return redirect('usr_role:patient')

class PatientDashboardView(TemplateView):
    template_name = 'user_role/patient_dashboard.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')  
        if not request.user.is_patient:
            return redirect('home')  
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_image'] = self.request.user.patient.patient_profile.url  
        return context

class DoctorDashboardView(TemplateView):
    template_name = 'user_role/doctor_dashboard.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('usr_role:login')  # Redirect to login if not authenticated
        if not request.user.is_doctor:
            return redirect('usr_role:success')  # Redirect to home if not a patient
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_image'] = self.request.user.doctor.doctor_profile.url
        return context

class LogoutView(RedirectView):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('usr_role:login'))

role_based_access/usr_role/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en-us">

<head>
    <meta charset="utf-8">
    <title>{% block title %} Homepage{% endblock %}</title>    <!-- use this block to change title of specific page -->

    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5">
    <meta name="description" content="This is meta description">
    <meta name="author" content="Themefisher">

    <!-- theme meta -->
    <meta name="theme-name" content="gleamquest" />

    <!-- plugins -->
    <link rel="preload" href="https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFWJ0bbck.woff2" style="font-display: optional;">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:600%7cOpen&#43;Sans&amp;display=swap" media="screen">

    <link rel="stylesheet" href="{% static 'themify-icons/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'slick/slick.css' %}">

    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!--Favicon-->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
</head>

<body>
    <!-- navigation -->
    <header class="sticky-top bg-white border-bottom border-default">
        <div class="container">
           <h1>{% block header %}Role Based Authentication{% endblock %}</h1>
        </div>
    </header>
    <!-- /navigation -->
    <section id="about-2" class="about-2 section bg-secondary">
        
        <div class="container">
            <div class="content">
              {% block content %}
            
              {% endblock %}    
        </div>
    </div>
</section>
    

    <!-- JS Plugins -->
    <script src="{% static 'jQuery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}" async></script>
    <script src="{% static 'slick/slick.min.js' %}"></script>

    <!-- Main Script -->
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

role_based_access/usr_role/templates/user_role/doctor_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block header %}{% endblock %}
{% block title%} Doctor Registration {% endblock %}

{% block content %}
    <div class="container bg-light">
        <h2 class="card-title text-center">Doctor Dashboard</h2>
      <div class="container">
        <div class="main-body">
        
              <!-- Breadcrumb -->
              <nav aria-label="breadcrumb" class="main-breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                  <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
                  <li class="breadcrumb-item active" aria-current="page">User Profile</li>
                </ol>
              </nav>
              <!-- /Breadcrumb -->
        
              <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                  <div class="card">
                    <div class="card-body">
                      <div class="d-flex flex-column align-items-center text-center">
                        <img src="{{profile_image}}" alt="Admin" class="rounded-circle" width="150">
                        <div class="mt-3">
                          <h4>{{user.username}}</h4>
                          <!-- <p class="text-secondary mb-1">Full Stack Developer</p> -->
                          <!-- <p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p> -->
                        <a class="btn btn-primary" href="{% url 'usr_role:logout' %}">Logout</a>
                          <!-- <button class="btn btn-outline-primary">Message</button> -->
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="card mb-3">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.first_name}}  {{user.last_name}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.email}}
                        </div>
                      </div>
                      <hr>
                      <!-- <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Phone</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          (239) 816-9029
                        </div>
                      </div> 
                      <hr>-->
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Mobile</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          (320) 380-4539
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          {{ user.address }}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-12">
                          <a class="btn btn-info " target="__blank" href="https://www.bootdey.com/snippets/view/profile-edit-data-and-skills">Edit</a>
                        </div>
                      </div>
                    </div>
                  </div>
    
                  <div class="row gutters-sm">
                    
                  </div>
    
    
    
                </div>
              </div>
    
            </div>
        </div>
    </div>
{% endblock %}

role_based_access/usr_role/templates/user_role/doctor_register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title%} Doctor Registration {% endblock %}

{% block content %}
    <div class="container bg-light">
        <h2 class="card-title text-center">Registration For Doctor</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            <div class="conatiner">
                {% csrf_token %}

                {{ form|crispy }}
            </div>

            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

role_based_access/usr_role/templates/user_role/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title%} User Login {% endblock %}

{% block content %}
    <div class="container bg-light">
        <h2 class="card-title text-center">Please Login</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            <div class="conatiner">
                {% csrf_token %}

                {{ form|crispy }}
            </div>

            <button class="btn btn-primary" type="submit">Submit</button>

            Not Registered ? <a style="color: black;" href="{% url 'usr_role:register' %}">register</a>
        </form>
    </div>
{% endblock %}

role_based_access/usr_role/templates/user_role/patient_dashboard.html
{% extends 'base.html' %}

{% load static %}
{% block header %}{% endblock %}
{% block title%} Patient Registration {% endblock %}

{% block content %}
<div class="container bg-light">
    <h2 class="card-title text-center">Patient Dashboard</h2>
  <div class="container">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{ profile_image }}" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{user.username}}</h4>
                     
                      <a class="btn btn-primary" href="{% url 'usr_role:logout' %}">Logout</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{user.first_name}}  {{user.last_name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{user.email}}
                    </div>
                  </div>
                  <hr>
                 
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      (320) 380-4539
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.address }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-info " target="__blank" href="https://www.bootdey.com/snippets/view/profile-edit-data-and-skills">Edit</a>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row gutters-sm">
                
              </div>
            </div>
          </div>

        </div>
    </div>
</div>
{% endblock %}

role_based_access/usr_role/templates/user_role/patient_register.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title%} Patient Registration {% endblock %}

{% block content %}
    <div class="container bg-light">
        <h2 class="card-title text-center">Registration For Patient</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            <div class="conatiner">
                {% csrf_token %}

                {{ form|crispy }}
            </div>
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

role_based_access/usr_role/templates/user_role/register.html
{% extends 'base.html' %}

{% load static %}

{% block title%} User Registration {% endblock %}


{% block content %}
    <div class="container">
        <form action="" method="POST" enctype="multipart/form-data">
            <div class="conatiner">
                <div class="card text-center">
                    <div class="card-body">
                      <h5 class="card-title">Choose Your Role</h5>
                      <a class="btn btn-primary" style="color:white;"  href="{% url 'usr_role:doctor_register' %}">Doctor</a>
                      <a class="btn btn-primary" style="color:white;" href="{% url 'usr_role:patient_register' %}">Patient</a>
                    </div>
                    <div class="card-footer text-muted">
                      Already have an account ? <a href="{% url 'usr_role:login' %}">login</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

role_based_access/usr_role/templates/user_role/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        !!!!! 404 ERROR !!!!!
    </h1>
</body>
</html>